version: "3.6"
services:
  metasquanch:
    build:
      context: .
      network: host
    ports:
      - "8000:8000"
    depends_on: redis
  nginx:
    image: "nginx:latest"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
  redis:
    image: "redis:latest"
